### ISSUE TITLE
8주차 https와 cors 과제 제출합니다.

### ISSUE THREAD

**Issue by fivedasol** [likelion-Inha-12/fivedasol#11]
![cors과제](https://github.com/likelion-Inha-12/fivedasol/assets/81301003/056928d9-ea20-4195-8e23-5285c6db0f84)

**Comment by fivedasol** [comment]
키워드 과제 : https://stingy-sun-32e.notion.site/w8-https-cors-9c8d92e47429456194f62d0ab3c449be?pvs=4

**Comment by juwon0403** [comment]
아주 야무지게 작성해주셨네용 ㅎ.ㅎ
URL, origin, domain 예시까지 들어서 잘 설명해주셨습니다!!!

수고하셨어용~~
