### ISSUE TITLE
7주차 배포 과제 제출합니다.

### ISSUE THREAD

**Issue by fivedasol** [likelion-Inha-12/fivedasol#9]
![배포_사진](https://github.com/likelion-Inha-12/fivedasol/assets/81301003/e68b0f80-ba98-4a40-a634-64d6141c6f8b)
![aws_인스턴스_info](https://github.com/likelion-Inha-12/fivedasol/assets/81301003/ce12c508-a3ce-470c-ab30-4afa3e9544ae)

**Comment by fivedasol** [comment]
그냥 탄력적 IP만 입력하면 404 에러가 뜨는데 /health/를 붙여주면 배포 성공한걸로 보여서 그 사진을 제출했습니다..!

**Comment by juwon0403** [comment]
조아요 조아요~~~
세션 잘 따라와주셔서 감사합니다,, 수고하셨어요!!!
